//
//  Day08Tests.swift
//  Advent of code 2024
//
//  Created by Iggy Drougge on 2024-12-08.
//

import Testing
import Advent2024

struct Day08Tests {
    @Test func testPart1WithTestInput() throws {
        #expect(
            Day08.part1(
                        """
                        ............
                        ........0...
                        .....0......
                        .......0....
                        ....0.......
                        ......A.....
                        ............
                        ............
                        ........A...
                        .........A..
                        ............
                        ............
                        """
            ) == 14
        )
    }
    
    @Test func testPart1() throws {
        #expect(
            Day08.part1(try Input(named: "Day08")) == 254
        )
    }
    
    @Test func testPart2WithTestInput() throws {
        #expect(
            Day08.part2(
                        """
                        ............
                        ........0...
                        .....0......
                        .......0....
                        ....0.......
                        ......A.....
                        ............
                        ............
                        ........A...
                        .........A..
                        ............
                        ............
                        """
            ) == 34
        )
    }
    
    @Test func testPart2WithSmallInput() throws {
        #expect(
            Day08.part2(
                        """
                        T.........
                        ...T......
                        .T........
                        ..........
                        ..........
                        ..........
                        ..........
                        ..........
                        ..........
                        ..........
                        """
            ) == 9
        )
    }
    
    @Test func testPart2() throws {
        #expect(
            Day08.part2(try Input(named: "Day08")) == 951
        )
    }
}
